version: '3.8'

services:
  fhir-validator:
    platform: linux/amd64
    image: markiantorno/validator-wrapper:1.0.70
    ports:
      - "3500:3500"
    environment:
      VALIDATION_SERVICE_PRESETS_FILE_PATH: /presets.json
    volumes:
      - ./data/config/validation/presets.json:/presets.json
    networks:
      - fhirnet
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3500/validator/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  validate-script:
    depends_on:
      fhir-validator:
        condition: service_healthy
    image: python:3.12-slim
    volumes:
      - ./scripts:/app
      - ./data/output/large:/data/output/large
      - ./data/output/validation_result:/validation_result
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
#    command: ["/bin/sh", "-c", "pip install requests && python validate.py /data/output/large"]
    networks:
      - fhirnet

networks:
  fhirnet:
    driver: bridge

