version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./data:/data
    environment:
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.Health.Fhir.Anonymizer=Trace
      - Logging__Console__IncludeScopes=true