version: '3.8'

services:
  fhir-de-identifier:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./fastapi-app:/app/fastapi-app
#    entrypoint: ["dotnet", "Microsoft.Health.Fhir.Anonymizer.R4.CommandLineTool.dll"]
