# Use 'docker compose' (v2+) instead of 'docker-compose' (v1, deprecated)
# All commands and documentation should reference 'docker compose'
# Example: docker compose -f docker-compose-validate.yml up --build -d

version: '3.8'

services:
  #  fhir-validator:
  #    platform: linux/amd64
  #    image: markiantorno/validator-wrapper:1.0.70
  #    ports:
  #      - "3500:3500"
  #    environment:
  #      VALIDATION_SERVICE_PRESETS_FILE_PATH: /presets.json
  #    volumes:
  #      - ./data/config/validation/presets.json:/presets.json
  #    networks:
  #      - fhirnet
  #    healthcheck:
  #      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3500/validator/version"]
  #      interval: 30s
  #      timeout: 10s
  #      retries: 3
  #      start_period: 60s

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=hapi
      - POSTGRES_USER=hapi
      - POSTGRES_PASSWORD=hapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fhirnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hapi"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  hapi-fhir:
    image: hapiproject/hapi:v8.4.0-2
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    configs:
      - source: hapi
        target: /app/config/application.yaml
    networks:
      - fhirnet

  validate-script:
    image: python:3.12-slim
    volumes:
      - ./profiles:/profiles
      - ./scripts:/app
      - ./data/input/large:/data/input
      - ./data/output/large:/data/output/large
      - ./data/validation_result:/validation_result
    working_dir: /app
    command: [ "sh", "-c", "apt-get update && apt-get install -y curl &&  tail -f /dev/null" ]
    networks:
      - fhirnet

networks:
  fhirnet:
    driver: bridge

volumes:
  pgdata:

configs:
  hapi:
     file: ./data/config/validation/application.yaml